### ISSUE TITLE
to-do list

### ISSUE THREAD

**Issue by saramortara** [familia-mortara/receitas_mortara#1]
- [x] Adicionar campos **Dicas** entre preparo e fonte 
- [x] Adicionar campo **Memórias** no início, após quem
- [x] **Tempo de preparo** em outra linha
- [x] Remover campos com NA da visualização
- [x] Formatação de itens com < Item > em preparo
- [x] Formatação de frações como fórmula
- [x] Legenda das dietas no início
- [x] Figuras da dieta antes dos ingredientes
- [ ] Incluir nova coluna de ingredientes com variações (adaptação ou porção)
- [ ] Adicionar figura em boa resolução
- [ ] Formatação de tópicos com > em preparo
